In [125]:
import import_ipynb
import Content_based_filtering as cf

In [174]:
top10ids=[]
dic=loadmat('top10.mat')

u_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code']
user_df = pd.read_csv('ml-100k/u.user', sep='|', names=u_cols,
                    encoding='latin-1', parse_dates=True)

movies_df=pd.read_csv('ml-100k/item_cc.csv')


def getusers(uname,movieid):

    rating=matrix.iloc[uname][movieid]
    print("you're going to rate this movie: ",rating)
    print("---------------------------------------------------------------------")
    print("your partners are (They also rated",rating,")")
    h=matrix.loc[matrix.iloc[:,movieid]==rating]
    l=h.index.tolist()
    with pd.option_context('display.max_rows', None, 'display.max_columns', None):
        display(user_df.loc[user_df['user_id'].isin(l)])
    print("---------------------------------------------------------------------")
    

def gettop(uname):
    print("You may like:")
    ll=dic[str(uname)][0]
    with pd.option_context('display.max_rows', None, 'display.max_columns', None):
        display(movies_df.loc[movies_df['movie_id'].isin(ll)])
    print("------------------------------------------------------")

def driver(uname, movieid=""):
    
    gettop(uname)
    if(movieid!=""):
        movietitle=movies_df.loc[movies_df['movie_id']==int(movieid),'movie_title'].iloc[0]
        
        getusers(uname,movieid)
        print("Similar movies are")
        ans=cf.get_recommendations(movietitle)
        
        lll=ans[0].tolist()
        df2=movies_df['movie_title'].str.lower().to_frame()
        df2=df2['movie_title'].str.strip().to_frame()
        df3=movies_df[['year','director','actor1','actor2']]
        df3=pd.concat([df2, df3], axis=1)


        with pd.option_context('display.max_rows', None, 'display.max_columns', None):
            display(df3.loc[df3['movie_title'].isin(lll)])
        print("-----------------------------------------------------")

driver(5,89)

You may like:

,movie_title,year,tmdb_id,movie_id,director,actor1,actor2
22,Taxi Driver,1996,103,23,Martin Scorsese,Robert De Niro,Jodie Foster
95,Terminator 2: Judgment Day,1991,280,96,James Cameron,Arnold Schwarzenegger,Linda Hamilton
136,Big Night,1996,18203,137,Stanley Tucci,Stanley Tucci,Tony Shalhoub
176,"Good, The Bad and The Ugly, The",1966,429,177,Sergio Leone,Clint Eastwood,Eli Wallach
198,"Bridge on the River Kwai, The",1957,826,199,David Lean,William Holden,Alec Guinness
222,Sling Blade,1996,12498,223,Billy Bob Thornton,Billy Bob Thornton,Dwight Yoakam
481,Casablanca,1942,289,483,Michael Curtiz,Humphrey Bogart,Ingrid Bergman
645,Ran,1985,11645,647,Akira Kurosawa,Tatsuya Nakadai,Akira Terao
654,M,1931,832,656,Fritz Lang,Peter Lorre,Ellen Widmann
1037,Hamlet,1997,10549,1039,Kenneth Branagh,Kenneth Branagh,Derek Jacobi

------------------------------------------------------
you're going to rate this movie:  4
---------------------------------------------------------------------
your partners are (They also rated 4 )

     user_id  age sex     occupation zip_code
0          1   24   M     technician    85711
1          2   53   F          other    94043
2          3   23   M         writer    32067
4          5   33   F          other    15213
6          7   57   M  administrator    91344
9         10   53   M         lawyer    90703
10        11   39   F          other    30329
11        12   28   F          other    06405
12        13   47   M       educator    29206
13        14   45   M      scientist    55106
15        16   21   M  entertainment    10309
17        18   35   F          other    37212
19        20   42   F      homemaker    95660
23        24   21   F         artist    94533
24        25   39   M       engineer    55107
25        26   49   M       engineer    21044
26        27   40   F      librarian    30030
27        28   32   M         writer    55369
29        30    7   M        student    55436
30        31   24   M         artist    10003
33        34   38   F  administrator    42141
35        36   19   F        student    93117
36        37   23   M        student    55105
37        38   28   F          other    54467
38        39   41   M  entertainment    01040
39        40   38   M      scientist    27514
40        41   33   M       engineer    80525
41        42   30   M  administrator    17870
43        44   26   M     technician    46260
45        46   27   F      marketing    46538
46        47   53   M      marketing    07102
48        49   23   F        student    76111
49        50   21   M         writer    52245
51        52   18   F        student    55105
52        53   26   M     programmer    55414
54        55   37   M     programmer    01331
55        56   25   M      librarian    46260
59        60   50   M     healthcare    06472
61        62   27   F  administrator    97214
63        64   32   M       educator    43202
64        65   51   F       educator    48118
66        67   17   M        student    60402
67        68   19   M        student    22904
68        69   24   M       engineer    55337
72        73   24   M        student    41850
73        74   39   M      scientist    T8H1N
74        75   24   M  entertainment    08816
76        77   30   M     technician    29379
77        78   26   M  administrator    61801
78        79   39   F  administrator    03755
79        80   34   F  administrator    52241
80        81   21   M        student    21218
81        82   50   M     programmer    22902
83        84   32   M      executive    55369
84        85   51   M       educator    20003
85        86   26   M  administrator    46005
86        87   47   M  administrator    89503
87        88   49   F      librarian    11701
89        90   60   M       educator    78155
91        92   32   M  entertainment    80525
96        97   43   M         artist    98006
97        98   49   F      executive    90291
98        99   20   M        student    63129
99       100   36   M      executive    90254
100      101   15   M        student    05146
101      102   38   M     programmer    30220
103      104   27   M        student    55108
104      105   24   M       engineer    94043
105      106   61   M        retired    55125
106      107   39   M      scientist    60466
107      108   44   M       educator    63130
108      109   29   M          other    55423
109      110   19   M        student    77840
110      111   57   M       engineer    90630
111      112   30   M       salesman    60613
114      115   31   M       engineer    17110
117      118   21   M  administrator    90210
118      119   32   M     programmer    67401
119      120   47   F          other    06260
120      121   54   M      librarian    99603
121      122   32   F         writer    22206
122      123   48   F         artist    20008
123      124   34   M        student    60615
124      125   30   M         lawyer    22202
126      127   33   M           none    73439
128      129   36   F      marketing    07039
130      131   59   F  administrator    15237
131      132   24   M          other    94612
132      133   53   M       engineer    78602
133      134   31   M     programmer    80236
134      135   23   M        student    38401
136      137   50   M       educator    84408
138      139   20   M        student    08904
139      140   30   F        student    32250
143      144   53   M     programmer    20910
144      145   31   M  entertainment    V3N4P
147      148   33   M       engineer    97006
148      149   35   F      marketing    17325
153      154   25   M        student    53703
154      155   32   F          other    11217
155      156   25   M       educator    08360
157      158   50   M       educator    27606
158      159   23   F        student    55346
160      161   50   M         lawyer    55104
161      162   25   M         artist    15610
164      165   20   F          other    53715
165      166   47   M       educator    55113
166      167   37   M          other    L9G2B
167      168   48   M          other    80127
169      170   53   F     healthcare    30067
173      174   30   F  administrator    52302
176      177   20   M     programmer    19104
177      178   26   M          other    49512
178      179   15   M  entertainment    20755
180      181   26   M      executive    21218
181      182   36   M     programmer    33884
182      183   33   M      scientist    27708
183      184   37   M      librarian    76013
186      187   26   M       educator    16801
188      189   32   M         artist    95014
189      190   30   M  administrator    95938
190      191   33   M  administrator    95161
191      192   42   M       educator    90840
193      194   38   M  administrator    02154
194      195   42   M      scientist    93555
197      198   21   F        student    55414
201      202   41   F       educator    60201
202      203   25   F        student    32301
203      204   52   F      librarian    10960
205      206   14   F        student    53115
206      207   39   M      marketing    92037
207      208   43   M       engineer    01720
209      210   39   M       engineer    03060
210      211   66   M       salesman    32605
212      213   33   M      executive    55345
213      214   26   F      librarian    11231
214      215   35   M     programmer    63033
216      217   22   M          other    11727
217      218   37   M  administrator    06513
218      219   32   M     programmer    43212
219      220   30   M      librarian    78205
221      222   29   M     programmer    27502
225      226   28   M        student    92103
226      227   46   M      executive    60659
227      228   21   F        student    22003
228      229   29   F      librarian    22903
229      230   28   F        student    14476
230      231   48   M      librarian    01080
233      234   60   M        retired    94702
235      236   44   F         writer    53214
236      237   49   M  administrator    63146
237      238   42   F  administrator    44124
238      239   39   M         artist    95628
239      240   23   F       educator    20784
241      242   33   M       educator    31404
243      244   28   M     technician    80525
244      245   22   M        student    55109
245      246   19   M        student    28734
248      249   25   M        student    84103
249      250   29   M      executive    95110
251      252   42   M       engineer    07733
252      253   26   F      librarian    22903
253      254   44   M       educator    42647
256      257   17   M        student    77005
257      258   19   F        student    77801
260      261   28   M  administrator    85202
261      262   19   F        student    78264
262      263   41   M     programmer    55346
263      264   36   F         writer    90064
264      265   26   M      executive    84601
266      267   23   M       engineer    83716
271      272   33   M      scientist    53706
275      276   21   M        student    95064
277      278   37   F      librarian    30033
278      279   33   M     programmer    85251
279      280   30   F      librarian    22903
280      281   15   F        student    06059
281      282   22   M  administrator    20057
282      283   28   M     programmer    55305
283      284   40   M      executive    92629
284      285   25   M     programmer    53713
286      287   21   M       salesman    31211
287      288   34   M      marketing    23226
292      293   24   M         writer    60804
295      296   43   F  administrator    16803
296      297   29   F       educator    98103
300      301   24   M        student    55439
301      302   42   M       educator    77904
302      303   19   M        student    14853
304      305   23   M     programmer    94086
307      308   60   M        retired    95076
308      309   40   M      scientist    70802
312      313   41   M      marketing    60035
313      314   20   F        student    08043
316      317   22   M  administrator    13210
317      318   65   M        retired    06518
318      319   38   M     programmer    22030
321      322   20   M        student    50613
323      324   21   F        student    02176
324      325   48   M     technician    02139
325      326   41   M  administrator    15235
327      328   51   M  administrator    06779
329      330   35   F       educator    33884
331      332   20   M        student    40504
332      333   47   M          other    V0R2M
333      334   32   M      librarian    30002
334      335   45   M      executive    33775
335      336   23   M       salesman    42101
336      337   37   M      scientist    10522
338      339   35   M         lawyer    37901
344      345   28   F      librarian    94143
345      346   34   M          other    76059
347      348   24   F        student    45660
348      349   68   M        retired    61455
351      352   37   F     programmer    55105
352      353   25   M      scientist    28480
354      355   25   M        student    60135
356      357   26   M      executive    98133
357      358   40   M       educator    10022
358      359   22   M        student    61801
359      360   51   M          other    98027
360      361   22   M        student    44074
361      362   35   F      homemaker    85233
362      363   20   M        student    87501
363      364   63   M       engineer    01810
366      367   17   M        student    37411
368      369   24   M        student    91335
369      370   52   M         writer    08534
373      374   36   M      executive    78746
374      375   17   M  entertainment    37777
375      376   28   F          other    10010
376      377   22   M        student    18015
377      378   35   M        student    02859
380      381   33   M         artist    94608
383      384   52   M     programmer    45218
384      385   36   M         writer    10003
386      387   33   M  entertainment    37412
387      388   31   M          other    36106
390      391   23   M        student    84604
394      395   43   M          other    44092
395      396   57   M       engineer    94551
396      397   17   M        student    27514
397      398   40   M          other    60008
398      399   25   M          other    92374
400      401   46   F     healthcare    84107
401      402   30   M       engineer    95129
402      403   37   M          other    06811
404      405   22   F     healthcare    10019
405      406   52   M       educator    93109
408      409   48   M  administrator    98225
410      411   34   M       educator    44691
411      412   25   M       educator    15222
416      417   27   F          other    48103
418      419   37   M         lawyer    43215
420      421   38   F     programmer    55105
421      422   26   M  entertainment    94533
422      423   64   M          other    91606
423      424   36   F      marketing    55422
424      425   19   M        student    58644
426      427   51   M         doctor    85258
427      428   28   M        student    55414
428      429   27   M        student    29205
429      430   38   M      scientist    98199
430      431   24   M      marketing    92629
431      432   22   M  entertainment    50311
433      434   16   F        student    49705
434      435   24   M       engineer    60007
437      438   51   F  administrator    43204
439      440   30   M          other    48076
440      441   50   M     technician    55013
441      442   22   M        student    85282
442      443   35   M       salesman    33308
444      445   21   M         writer    92653
446      447   30   M  administrator    55113
451      452   35   M  administrator    28018
454      455   48   M  administrator    83709
456      457   33   F       salesman    30011
457      458   47   M     technician    Y1A6B
458      459   22   M        student    29201
459      460   44   F          other    60630
462      463   48   F     healthcare    75218
463      464   60   M         writer    94583
465      466   22   M        student    90804
466      467   29   M       engineer    91201
468      469   60   M       educator    78628
469      470   24   M     programmer    10021
471      472   24   M        student    87544
473      474   51   M      executive    93711
474      475   30   M     programmer    75230
476      477   23   F        student    02125
477      478   29   M          other    10019
478      479   30   M       educator    55409
479      480   57   M        retired    98257
480      481   73   M        retired    37771
482      483   29   M      scientist    43212
483      484   27   M        student    21208
484      485   44   F       educator    95821
485      486   39   M       educator    93101
486      487   22   M       engineer    92121
489      490   29   F         artist    V5A2B
490      491   43   F         writer    53711
491      492   57   M       educator    94618
492      493   22   M       engineer    60090
495      496   21   F        student    55414
497      498   26   M         writer    55408
498      499   42   M     programmer    75006
499      500   28   M  administrator    94305
500      501   22   M        student    10025
501      502   22   M        student    23092
502      503   50   F         writer    27514
503      504   40   F         writer    92115
506      507   18   F         writer    28450
508      509   23   M  administrator    10011
509      510   34   M          other    98038
510      511   22   M        student    21250
512      513   43   M  administrator    26241
513      514   27   M     programmer    20707
514      515   53   M      marketing    49508
515      516   53   F      librarian    10021
516      517   24   M        student    55454
518      519   22   M          other    55320
520      521   19   M        student    02146
523      524   56   M       educator    02159
524      525   27   F  administrator    19711
525      526   30   M      marketing    97124
526      527   33   M      librarian    12180
528      529   47   F  administrator    44224
529      530   29   M       engineer    94040
530      531   30   F       salesman    97408
531      532   20   M        student    92705
533      534   20   M        student    05464
534      535   45   F       educator    80302
535      536   38   M       engineer    30078
536      537   36   M       engineer    22902
537      538   31   M      scientist    21010
538      539   53   F  administrator    80303
540      541   19   F        student    84302
541      542   21   M        student    60515
542      543   33   M      scientist    95123
546      547   50   M       educator    14534
547      548   51   M         writer    95468
549      550   16   F        student    95453
550      551   25   M     programmer    55414
552      553   58   M       educator    62901
553      554   32   M      scientist    62901
554      555   29   F       educator    23227
555      556   35   F       educator    30606
557      558   56   F         writer    63132
559      560   32   M        student    10003
561      562   54   F  administrator    20879
562      563   39   F      librarian    32707
564      565   40   M        student    55422
566      567   24   M  entertainment    10003
567      568   39   M       educator    01915
568      569   34   M       educator    91903
569      570   26   M       educator    14627
570      571   34   M         artist    01945
571      572   51   M       educator    20003
572      573   68   M        retired    48911
573      574   56   M       educator    53188
574      575   33   M      marketing    46032
575      576   48   M      executive    98281
578      579   32   M       educator    48103
579      580   16   M        student    17961
580      581   37   M          other    94131
582      583   44   M       engineer    29631
583      584   25   M        student    27511
584      585   69   M      librarian    98501
585      586   20   M        student    79508
586      587   26   M          other    14216
587      588   18   F        student    93063
588      589   21   M         lawyer    90034
589      590   50   M       educator    82435
590      591   57   F      librarian    92093
591      592   18   M        student    97520
592      593   31   F       educator    68767
593      594   46   M       educator    M4J2K
594      595   25   M     programmer    31909
595      596   20   M         artist    77073
596      597   23   M          other    84116
599      600   34   M     programmer    02320
602      603   21   M     programmer    47905
603      604   39   M       educator    11787
605      606   28   M     programmer    63044
606      607   49   F     healthcare    02154
608      609   13   F        student    55106
609      610   22   M        student    21227
610      611   46   M      librarian    77008
612      613   37   F      marketing    29678
613      614   54   M       educator    80227
614      615   38   M       educator    27705
615      616   55   M      scientist    50613
617      618   15   F        student    44212
618      619   17   M        student    44134
621      622   25   M     programmer    14850
622      623   50   F       educator    60187
623      624   19   M        student    30067
627      628   13   M           none    94306
628      629   46   F          other    44224
629      630   26   F     healthcare    55408
630      631   18   F        student    38866
631      632   18   M        student    55454
632      633   35   M     programmer    55414
633      634   39   M       engineer    T8H1N
636      637   30   M          other    74101
639      640   20   M        student    61801
643      644   51   M        retired    63645
644      645   27   M     programmer    53211
645      646   17   F        student    51250
646      647   40   M       educator    45810
647      648   43   M       engineer    91351
648      649   20   M        student    39762
649      650   42   M       engineer    83814
650      651   65   M        retired    02903
652      653   31   M      executive    55105
653      654   27   F        student    78739
655      656   48   M       educator    10314
656      657   26   F           none    78704
657      658   33   M     programmer    92626
661      662   55   M      librarian    19102
663      664   30   M       engineer    94115
664      665   25   M  administrator    55412
665      666   44   M  administrator    61820
666      667   35   M      librarian    01970
667      668   29   F         writer    10016
668      669   37   M          other    20009
670      671   21   M     programmer    91919
671      672   54   F  administrator    90095
672      673   51   M       educator    22906
673      674   13   F        student    55337
674      675   34   M          other    28814
675      676   30   M     programmer    32712
676      677   20   M          other    99835

---------------------------------------------------------------------
Similar movies are
88

,movie_title,year,director,actor1,actor2
6,twelve monkeys,1995,Terry Gilliam,Bruce Willis,Madeleine Stowe
49,star wars,1977,George Lucas,Mark Hamill,Harrison Ford
171,"empire strikes back, the",1980,Irvin Kershner,Mark Hamill,Harrison Ford
174,brazil,1985,Terry Gilliam,Jonathan Pryce,Robert De Niro
178,"clockwork orange, a",1971,Stanley Kubrick,Malcolm McDowell,Patrick Magee
180,return of the jedi,1997,Richard Marquand,Mark Hamill,Harrison Ford
182,alien,1979,Ridley Scott,Tom Skerritt,Sigourney Weaver
227,star trek: the wrath of khan,1982,Nicholas Meyer,William Shatner,Leonard Nimoy
324,g.i. jane,1997,Ridley Scott,Demi Moore,Viggo Mortensen
421,e.t. the extra-terrestrial,1982,Steven Spielberg,Henry Thomas,Drew Barrymore
486,sunset blvd.,1950,Billy Wilder,William Holden,Gloria Swanson
550,species,1995,Roger Donaldson,Natasha Henstridge,Ben Kingsley
689,dark city,1998,Alex Proyas,Rufus Sewell,William Hurt
758,screamers,1995,Christian Duguay,Peter Weller,Roy Dupuis
922,white squall,1996,Ridley Scott,Jeff Bridges,Caroline Goodall

-----------------------------------------------------